# Generated by Django 4.2.11 on 2024-05-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('categorie', models.TextField(null=True)),
                ('price', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'furniture',
                'verbose_name_plural': 'furnitures',
                'ordering': ['id'],
            },
        ),
    ]
