# Generated by Django 4.2.13 on 2024-05-13 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='ice_creams',
        ),
        migrations.AddField(
            model_name='icecream',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ice_cream_app.shop'),
            preserve_default=False,
        ),
    ]
